/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ManufacturerModel { 
    createdBy: string;
    createdOn: Date;
    id?: number;
    manufacturerAddress?: string;
    manufacturerJson?: string;
    manufacturerName: string;
    manufacturerOid: string;
    manufacturerUrl?: string;
    organizationOid: string;
    updatedBy?: string;
    updatedOn?: Date;
}
